### ISSUE TITLE
/.local/lib/python3.8/site-packages/scenic/simulators/carla/behaviors.scenic

### ISSUE THREAD

**Issue by lym-ay** [BerkeleyLearnVerify/Scenic#94] opened 2022-09-22 08:41 UTC
when I run carlaChallenge4.scenic, the error is "NameError: name '_model' is not defined".But I can't find _model,who tell me where is _model

**Comment by lym-ay** [comment] 2022-09-22 08:42
FYI

**Comment by Eric-Vin** [comment] 2024-03-25 18:27
Closing this as I am unable to reproduce the issue. Please file a new issue with the new template if this problem persists.

**Closed by Eric-Vin** 2024-03-25 18:27 UTC
