### ISSUE TITLE
TypeError: a bytes-like object is required, not 'list'

### ISSUE THREAD

**Issue by Nancy22-NJ** [BerkeleyLearnVerify/Scenic#177] opened 2023-09-13 09:11 UTC
Hello, i have problem on encoding the scene as bytes. 
The following are the codes and its error message. 
Looking forward to your reply!
**data = scenario.sceneToBytes(scene)**
**TypeError: a bytes-like object is required, not 'list'**

**Comment by Eric-Vin** [comment] 2023-09-13 15:24
Hello,

Could you provide a code snippet that triggers this error? I'm able to serialize scenes on my machine so I'm unsure where the problem might be. Once I can reproduce the issue I'm happy to help further!

**Comment by wlxxi** [comment] 2023-09-14 06:37
**scenario = scenic.scenarioFromFile(task, params=dict, mode2D=True)
                    scene, _ = scenario.generate()
                    
                    data = scenario.sceneToBytes(scene)
                    with open(pathlib.Path(tempfile.gettempdir()) / 'record/test.scene', 'wb') as f:
                        f.write(data)**
I was trying to store this scene.

**Comment by Eric-Vin** [comment] 2023-09-14 19:09
I'm able to serialize one of our driving examples with this script, so I'm not sure what the problem is. Can you print out what scene is?

**Comment by wlxxi** [comment] 2023-09-15 01:50
> I'm able to serialize one of our driving examples with this script, so I'm not sure what the problem is. Can you print out what scene is?
`
param map = localPath('../assets/maps/CARLA/Town04.xodr')
param carla_map = 'Town04'
param weather = 'WetCloudyNoon'
model scenic.simulators.carla.model

## CONSTANTS
# Ego Car
EGO_MODEL = "vehicle.lincoln.mkz_2017"
EGO_SPEED = 60
EGO_BRAKING_THRESHOLD = 10

# Background Car
BC_MODEL = "vehicle.tesla.cybertruck"
param BC_V = [20, 40, 40, 20]
param BC_DIST = 40
BC_BRAKING_THRESHOLD = 10

BRAKE_ACTION = 1.0

## DEFINING BEHAVIORS
# EGO BEHAVIOR: Follow lane, and brake after passing a threshold distance to the leading car, terminate when collision take place
behavior EgoBehavior():
    try:
        do FollowLaneBehavior(EGO_SPEED)

    interrupt when withinDistanceToAnyCars(self, EGO_BRAKING_THRESHOLD):
         take SetBrakeAction(BRAKE_ACTION)


# BV BEHAVIOR: fix route, vary velocity
behavior BackgroundCarBehavior():

        do FollowLaneBehavior(globalParameters.BC_V[0]) for 100 steps
        do FollowLaneBehavior(globalParameters.BC_V[1]) for 100 steps
        do FollowLaneBehavior(globalParameters.BC_V[2]) for 100 steps
        do FollowLaneBehavior(globalParameters.BC_V[3]) for 100 steps


## DEFINING SPATIAL RELATIONS

laneSecsWithRightLane = []
for lane in network.lanes:
    for laneSec in lane.sections:
        if laneSec._laneToRight is not None :
            if laneSec._laneToRight.isForward is laneSec.isForward:
                laneSecsWithRightLane.append(laneSec)

assert len(laneSecsWithRightLane) > 0, \
    'No lane sections with adjacent right lane with traffic direction in network.'

initLaneSec = Uniform(*laneSecsWithRightLane)
rightLaneSec = initLaneSec._laneToRight

egoSpot = new OrientedPoint on initLaneSec.centerline


ego = new Car on egoSpot,
    facing 0 deg relative to roadDirection,
    with blueprint EGO_MODEL,
    with behavior EgoBehavior()
ego.allowCollisions = True

bcSpot = new OrientedPoint right of ego by 1.5

bc = new Car following roadDirection from bcSpot for globalParameters.BC_DIST,
    facing 0 deg relative to roadDirection,
    with blueprint BC_MODEL,
    with behavior BackgroundCarBehavior()
bc.allowCollisions = True

require (distance to intersection) > 200
require ego can see bc`
I tried to vary the BV's velocity every 100 timesteps. The BV is on the right of the EGO.

**Comment by Eric-Vin** [comment] 2023-09-15 02:40
Oh sorry, I meant could you print out the variable `scene` before you try to serialize it?

**Comment by Nancy22-NJ** [comment] 2023-09-15 02:52
How to print the scene? Sorry, i'm not familiar with scenic. But I can print the attributes of SimulationResult.

**Comment by Eric-Vin** [comment] 2023-09-15 18:11
No problem! I was thinking something along the lines of:
```
scenario = scenic.scenarioFromFile(task, params=dict, mode2D=True)
scene, _ = scenario.generate()
print(scene)
```

**Comment by Nancy22-NJ** [comment] 2023-09-19 08:20
> No problem! I was thinking something along the lines of:
> 
> ```
> scenario = scenic.scenarioFromFile(task, params=dict, mode2D=True)
> scene, _ = scenario.generate()
> print(scene)
> ```

After printing the scene, it shows '<scenic.core.scenarios.Scene object at 0x7f2b7379f580>'

**Comment by Nancy22-NJ** [comment] 2023-09-19 11:22
@Eric-Vin Sorry to bother you, I wonder if only the static scenes can be serialized? Because i can't serialize the examples in the folder of NHTSA_Scenarios too. Thank you for your time.

**Comment by Eric-Vin** [comment] 2023-09-20 16:50
All scenes should be serializable, but if you want to serialize a simulation you'd need the `simulationToBytes` method. Can you include the .scenic file from above in a code block so I can debug on my end? The one you posted above has lost all formatting so it's hard to extract.

**Comment by Nancy22-NJ** [comment] 2023-09-21 01:56
> All scenes should be serializable, but if you want to serialize a simulation you'd need the `simulationToBytes` method. Can you include the .scenic file from above in a code block so I can debug on my end? The one you posted above has lost all formatting so it's hard to extract.

`The python file:
import scenic, tempfile, pathlib
scenario = scenic.scenarioFromFile('carlaChallenge1.scenic', mode2D=True)
scene, _ = scenario.generate()
simulator = scenario.getSimulator()
simulation = simulator.simulate(scene, maxSteps=200)
data = scenario.simulationToBytes(simulation)
with open(pathlib.Path(tempfile.gettempdir()) / 'test.scene', 'wb') as f:
        f.write(data)
The scenic file (from the Carla_challenge):
## SET MAP AND MODEL (i.e. definitions of all referenceable vehicle types, road library, etc)
param map = localPath('../../../assets/maps/CARLA/Town01.xodr')
param carla_map = 'Town01'
model scenic.simulators.carla.model

## CONSTANTS
EGO_MODEL = "vehicle.lincoln.mkz_2017"
EGO_SPEED = 10

## DEFINING BEHAVIORS
# EGO BEHAVIOR: Follow lane
behavior EgoBehavior(speed=10):
    do FollowLaneBehavior(speed)

## DEFINING SPATIAL RELATIONS
# Please refer to scenic/domains/driving/roads.py how to access detailed road infrastructure
# 'network' is the 'class Network' object in roads.py

# make sure to put '*' to uniformly randomly select from all elements of the list, 'lanes'
lane = Uniform(*network.lanes)

start = new OrientedPoint on lane.centerline
ego = new Car at start,
    with blueprint EGO_MODEL,
    with behavior EgoBehavior(EGO_SPEED)

debris1 = new Debris following roadDirection for Range(10, 20)
debris2 = new Debris following roadDirection from debris1 for Range(5, 10)
debris3 = new Debris following roadDirection from debris2 for Range(5, 10)

require (distance to intersection) > 50
terminate when (distance from debris3 to ego) > 10 and (distance to start) > 50
`
The error is scenic.core.serialization.SerializationError: Orientation type does not implement serialization

**Comment by Eric-Vin** [comment] 2023-09-21 18:13
Oh perfect! I'm not sure what changed to cause this new error but that's an error that I'm currently working on patching. It should be merged in soon, but if you'd like to try it sooner you can checkout the code on [this](https://github.com/BerkeleyLearnVerify/Scenic/tree/3DSerialization) branch. Please let me know id this resolves your issue!

**Comment by Eric-Vin** [comment] 2023-10-06 19:26
@Nancy22-NJ The PR with a fix has been merged into main. Please feel free to re-open this issue if you're still experiencing the bug.

**Closed by Eric-Vin** 2023-10-06 19:26 UTC
Labels: bug
